# Logging configuration
experiment_name: torchrl_chem
agent_name: reinvent
log_dir: logs_reinvent
logger_backend: null
seed: 101

# Environment configuration
num_envs: 128
molscore: MolOpt
detect_repeated_smiles: True  # Slows down the training and increase the memory usage
penalize_repeated_smiles: False
repetition_penalty: 0.5
prior: morgan.ckpt
vocabulary: morgan_vocabulary.txt

# Collector configuration
total_smiles: 12800

# Reinforce configuration
lr: 0.0001
eps: 1.0e-08
weight_decay: 0.0
sigma: 120

# Replay configuration
replay_buffer_size: 100
experience_replay: True
replay_batch_size: 10
