# Logging configuration
experiment_name: torchrl_chem
agent_name: ppo
log_dir: logs_ppo
logger_backend: wandb
seed: 101

# Environment configuration
num_env_workers: 32

# Collector configuration
total_frames: 2_000_000
frames_per_batch: 3840

# PPO configuration
lr: 0.0001
eps: 1e-04
weight_decay: 1e-4
gamma: 0.999
lmbda: 0.95
critic_coef: 0.25
entropy_coef: 0.01
kl_coef: 0.01
mini_batch_size: 8
ppo_epochs: 2
max_grad_norm: 1.0
ppo_clip: 0.2