# Logging configuration
experiment_name: generative_chemistry_ppo
agent_name: ppo
wandb_key: null
log_dir: generative_chemistry_ppo

# Environment configuration
num_env_workers: 8

# Collector configuration
total_frames: 1_000_000
frames_per_batch: 256

# PPO configuration
lr: 0.001
gamma: 0.99
lmbda: 0.95
critic_coef: 0.5
entropy_coef: 0.01
mini_batch_size: 128
ppo_epochs: 2