# Logging configuration
experiment_name: torchrl_chem
agent_name: sac
log_dir: logs_sac
logger_backend: null
seed: 101

# Environment configuration
num_env_workers: 2
molscore: /home/abou/MolScore/molscore/configs/GuacaMol/Albuterol_similarity.json

# Model
model: sac

# Collector configuration
total_frames: 20_000_000
frames_per_batch: 2000

# Replay buffer configuration
replay_buffer_size: 100_000

# Discrete SAC configuration
lr: 0.0001
eps: 1e-04
weight_decay: 1e-4
gamma: 0.99
target_update_polyak: 0.95
target_entropy_weight: 0.5
batch_size: 2
kl_coef: 0.01
max_grad_norm: 1.0
num_loss_updates: 1
