# Logging configuration
experiment_name: torchrl_chem
agent_name: sac
log_dir: logs_sac
logger_backend: null
seed: 101

# Environment configuration
num_env_workers: 32
molscore: /home/abou/MolScore/molscore/configs/GuacaMol/Albuterol_similarity.json

# Model
model: sac

# Collector configuration
total_frames: 20_000_000
frames_per_batch: 3840

# Discrete SAC configuration
target_entropy_weight: 0.5
