# Logging configuration
experiment_name: acegen
agent_name: reinvent
log_dir: logs_reinvent
logger_backend: null # csv, wandb, tensorboard, or null
seed: 101

# Environment configuration
num_envs: 128
molscore: LibINVENT_Exp1
molscore_include: null 

# Promptsmiles configuration
promptsmiles: "Fc1ccc(*)cc1.C(*)C(O)CC(O)CC(=O)O" # Scaffold N1(*)CCN(CC1)CCCCN(*)
promptsmiles_optimize: True
promptsmiles_shuffle: True
promptsmiles_multi: True

# Collector configuration
total_smiles: 10_000

# Architecture
model: gru # gru, lstm, or gpt2
# The default prior varies for each model. Refer to the README file in the root directory for more information.
# The default vocabulary varies for each prior. Refer to the README file in the root directory for more information.

# Reinforce configuration
lr: 0.0001
eps: 1.0e-08
weight_decay: 0.0
sigma: 120

# Replay configuration
replay_buffer_size: 100
experience_replay: True
replay_batch_size: 10
