experiment_name: pretrain
agent_name: gru
seed: 101

train_dataset_path: /shared/albert/acegen-open/priors/smiles_test_set
recompute_dataset: True
dataset_log_dir: /tmp/pretrain
model_log_dir: /tmp/pretrain
logger: null

lr: 0.0001
lr_decay_per_epoch: 1.0 # no decay
epochs: 10
batch_size: 8
randomize_smiles: False
num_test_smiles: 100
