experiment_name: pretrain
agent_name: gru

train_dataset_path: null
dataset_log_dir: /tmp/pretrain
model_log_dir: /tmp/pretrain
logger: null

lr: 0.0001
epochs: 10
batch_size: 128
randomize_smiles: False
