experiment_name: pretrain
agent_name: gru
seed: 101

dataset_path: smiles_test_set
recompute_dataset: True
dataset_log_dir: /tmp/pretrain
model_log_dir: /tmp/pretrain
logger: null

lr: 0.0001
epochs: 10
batch_size: 8
randomize_smiles: False
num_test_smiles: 100
