# Logging configuration
experiment_name: torchrl_open
agent_name: a2c
log_dir: logs_a2c
logger_backend: null
seed: 101

# Environment configuration
num_envs: 4
molscore: MolOpt
molscore_include: null
prior: chembl_filtered.ckpt
vocabulary: chembl_filtered_vocabulary.txt

# Collector configuration
total_smiles: 10_000
frames_per_batch: 400

# Architecture configuration
model: gru
shared_nets: True

# Optimizer
lr: 0.0005
eps: 1.0e-06
weight_decay: 1.0e-06

# A2C configuration
gamma: 0.999
lmbda: 0.99
critic_coef: 0.5
entropy_coef: 0.05
kl_coef: 0.5
mini_batch_size: 4
max_grad_norm: 1.0
