# Logging configuration
experiment_name: torchrl_chem
agent_name: a2c
log_dir: logs_a2c
logger_backend: null
seed: 101

# Environment configuration
num_envs: 4
molscore: /home/abou/MolScore/molscore/configs/GuacaMol/Albuterol_similarity.json
penalize_repetition: False
repetition_penalty: 0.5

# Collector configuration
total_frames: 1_000_000
frames_per_batch: 400

# Architecture configuration
shared_nets: True

# Optimizer
lr: 0.0005
eps: 1.0e-08
weight_decay: 1.0e-08

# A2C configuration
gamma: 0.999
lmbda: 0.95
critic_coef: 0.5
entropy_coef: 0.05
kl_coef: 0.5
mini_batch_size: 4
max_grad_norm: 1.0
experience_replay: True
replay_batches: 1
replay_frequency: 4
loss_critic_type: l2
