# Logging configuration
experiment_name: torchrl_chem
agent_name: dqn
log_dir: logs_dqn
logger_backend: null
seed: 101

# Environment configuration
num_envs: 10
vocabulary: morgan_vocabulary.txt
molscore: /shared/albert/MolScore/molscore/configs/valid.json
prior: ckpt_240000.pt

# Collector configuration
total_smiles: 12800
frames_per_batch: 1000
init_random_smiles: 500

# Replay buffer configuration
replay_buffer_size: 10_000

# DQN configuration
lr: 0.001
eps: 1e-08
weight_decay: 1e-8
gamma: 0.999
target_update_polyak: 0.95
batch_size: 32
sampled_sequence_length: 11 # Unused
burn_in: 10
max_grad_norm: 10.0
num_loss_updates: 100
value_network_update_interval: 1000
