# Logging configuration
experiment_name: torchrl_chem
agent_name: reinvent
log_dir: logs_reinvent
logger_backend: null
seed: 101

# Environment configuration
num_envs: 64
molscore: /shared/albert/MolScore/molscore/configs/GuacaMol/Albuterol_similarity.json
penalize_repetition: False
repetition_penalty: 0.5
prior: morgan.ckpt
vocabulary: morgan_vocabulary.txt

# Collector configuration
total_frames: 12800

# Reinforce configuration
lr: 0.0005
eps: 1.0e-08
topk: 0.5
weight_decay: 0.0
sigma: 500

# Replay configuration
replay_buffer_size: 100
experience_replay: True
replay_batch_size: 4
