# Logging configuration
experiment_name: torchrl_open
agent_name: ahc
log_dir: logs_ahc
logger_backend: null
seed: 101

# Environment configuration
num_envs: 128
molscore: MolOpt
molscore_include: null
prior: morgan.ckpt
vocabulary: morgan_vocabulary.txt

# Collector configuration
total_smiles: 10_000

# Architecture
model: gru

# AHC configuration
lr: 0.0001
eps: 1.0e-08
topk: 0.5
weight_decay: 0.0
sigma: 60

# Replay configuration
replay_buffer_size: 100
experience_replay: True
replay_batch_size: 10
