# Logging configuration
experiment_name: torchrl_chem
agent_name: ahc
log_dir: logs_ahc
logger_backend: null
seed: 101

# Environment configuration
num_envs: 64
molscore: /home/abou/MolScore/molscore/configs/GuacaMol/Albuterol_similarity.json

# Model
model: ahc

# Collector configuration
total_frames: 12800
frames_per_batch: 64


# Reinforce configuration
lr: 0.0005
eps: 1.0e-08
weight_decay: 0.0
sigma: 60
topk: 0.5
experience_replay: false
