# Logging configuration
experiment_name: torchrl_chem
agent_name: reinvent
log_dir: logs_reinvent
logger_backend: wandb
seed: 101

# Environment configuration
num_envs: 64
molscore: /home/abou/MolScore/molscore/configs/GuacaMol/Albuterol_similarity.json

# Model
model: reinvent

# Collector configuration
total_frames: 12800

# Reinforce configuration
lr: 0.0005
eps: 1.0e-08
weight_decay: 0.0
sigma: 500
experience_replay: True
replay_batch_size: 4
