# Logging configuration
experiment_name: pretrain
agent_name: gru
logger_backend: null # csv, wandb, tensorboard, or null
seed: 101
dataset_log_dir: /tmp/pretrain
model_log_dir: /tmp/pretrain

# Dataset configuration
train_dataset_path: null

# Model configuration
model: gru # gru, lstm, or gpt2

# Training configuration
lr: 0.0001
lr_decay_per_epoch: 1.0 # no decay
epochs: 10
batch_size: 8
randomize_smiles: False
num_test_smiles: 100
