agent_name: reinvent
eps: 1.0e-08
experience_replay: true
experiment_name: torchrl_open
log_dir: logs_reinvent
logger_backend: null
lr: 0.0001
model: gru
molscore: MolOpt
molscore_include: null
num_envs: 128
prior: gru_chembl_filtered.ckpt
replay_batch_size: 10
replay_buffer_size: 100
seed: 101
sigma: 120
total_smiles: 10000
vocabulary: chembl_filtered_vocabulary.txt
weight_decay: 0.0
