# Logging configuration
experiment_name: torchrl_chem
agent_name: sac
log_dir: logs_sac
logger_backend: null
seed: 101

# Environment configuration
num_envs: 10
molscore: /home/abou/MolScore/molscore/configs/GuacaMol/Albuterol_similarity.json

# Collector configuration
total_smiles: 12800
frames_per_batch: 1000
init_random_smiles: 20

# Replay buffer configuration
replay_buffer_size: 10_000

# Architecture configuration
shared_nets: True

# Discrete SAC configuration
lr: 0.0005
eps: 1e-06
weight_decay: 0.0
gamma: 0.999
target_update_polyak: 0.995
target_entropy_weight: 0.1
sampled_sequence_length: 20  # Unused
burn_in: 0
batch_size: 4
kl_coef: 0.5
max_grad_norm: 1.0
num_loss_updates: 500
value_loss_function: l2
actor_updates_frequency: 1
