# Logging configuration
experiment_name: torchrl_chem
agent_name: sac
log_dir: logs_sac
logger_backend: null
seed: 101

# Environment configuration
num_envs: 1
molscore: /home/abou/MolScore/molscore/configs/GuacaMol/Albuterol_similarity.json

# Collector configuration
total_frames: 1_000_000
frames_per_batch: 100
init_random_smiles: 500

# Replay buffer configuration
replay_buffer_size: 10_000

# Discrete SAC configuration
lr: 0.0001
eps: 1e-06
weight_decay: 0.0
gamma: 0.999
target_update_polyak: 0.95
target_entropy_weight: 0.1
sampled_sequence_length: 20
burn_in: 10
batch_size: 4
kl_coef: 0.01
max_grad_norm: 1.0
num_loss_updates: 100
